#Site settings
name: Roger Garcia, Personal Website

# Build settings
markdown: kramdown
permalink: /tidbits/:year/:month/:day/:title
highlighter: rouge
future: true

collections:
  notes:
    output: true

sass:
    sass_dir: css
